Riaduievv: hw 14
eugene-okulik/VladVlad pull request #13
Opened 2024-04-02 20:39 UTC by RiaduievV

2024-04-03 17:37 UTC, eugene-okulik requested changes
Две проблемы:

1. Работа с базой данных из питона - это следующее занятие
2. Но я бы мог посмотреть и в питоновском коде те запросы, которые нужно было сделать, но ты сделал не все запросы.

2024-04-04 10:34 UTC, eugene-okulik approved these changes
В общем, с последовательностью есть вопросики, но разберешься с ними в следующем задании

2024-04-04 10:34 UTC, eugene-okulik commented on homework/riaduievv/hw_14/task_2.txt
> +INSERT INTO students (name, second_name, group_id) values ('Bob', 'Smith', 809)
А что за id группы ты здесь использовал? Ведь группу ты создаешь уже строкой ниже.

2024-04-04 10:34 UTC, merged

2024-04-04 14:18 UTC, RiaduievV commented on homework/riaduievv/hw_14/task_2.txt
> +INSERT INTO students (name, second_name, group_id) values ('Bob', 'Smith', 809)
Сделал как в уроке. номер группы. Просто в видео ты говорил, что группы ещё нет и наперёд поставил id 1

2024-04-05 08:05 UTC, eugene-okulik commented on homework/riaduievv/hw_14/task_2.txt
> +INSERT INTO students (name, second_name, group_id) values ('Bob', 'Smith', 809)
Я в уроке демонстрировал, что так не работает, если база пустая. Если у нас нет того, что указать, мы можем указать NULL